name: Deploy to IRIS DEV Environment

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to InterSystems IRIS DEV server (LINUX) 
    strategy:
      matrix:
        include:
          - servertag: dev 
            runner: [self-hosted, linux, x64, dev]
    runs-on: ${{ matrix.runner }}
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6


      - name: Create Terminal Script (LINUX)
        shell: bash
        run: |
          cat > "${GITHUB_WORKSPACE}/deploy.scr" <<EOF
          ${IRIS_USER}
          ${IRIS_PASSWORD}
          if \$SYSTEM.Mirror.IsPrimary() do ##class(SourceControl.Git.API).Pull(1)
          halt
          EOF
          echo "Terminal script created successfully"
      
      - name: Make script executable (LINUX)
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/deploy.scr"
          
      - name: Deploy to IRIS Dev Server (LINUX)
        shell: bash
        run: |
          iristermPath="/usr/irissys/bin/irisdb"
          scriptPath="${GITHUB_WORKSPACE}/deploy.scr"
          irisMgrPath="/usr/irissys/mgr"
          
          echo "Executing IRIS deployment..."
          echo "IRIS Path: ${iristermPath}"
          echo "Script: ${scriptPath}"
          
          "${iristermPath}" -s "${irisMgrPath}" -U CTI \
              < "${scriptPath}" \
              > "${GITHUB_WORKSPACE}/deployment.log"
          
          rc=$?
          
          if [ $rc -ne 0 ]; then
              echo "IRIS deployment failed with exit code $rc" >&2
              exit $rc
          fi     
      
      - name: Display Deployment Log (LINUX)
        if: always()
        shell: powershell
        run: |
          logPath="${GITHUB_WORKSPACE}/deployment.log"
          if [ -f "$logPath" ]; then
              echo
              echo "=== Deployment Log ==="
              cat "$logPath"
          else
              echo "No deployment log found"
          fi   
